### ISSUE TITLE
你好，你的jar包不全，怎么还有ibatis的包，beanutils的包也没有

### ISSUE THREAD

**Issue by YuHangZM** [JaceyRx/Examination_System#1]
我使用的是eclipse最新的版本，解决了项目的导入问题，但是将项目部署到Tomcat中的时候，总是报错，其中的报错都是和tomcat相关的，我已经去掉了servlet-api的引用。你能将项目布置成   在eclipse中的么？我感觉是包的问题，但是有找不到哪里出了问题。谢谢！

**Comment by JaceyRx** [comment]
包是没问题的 servlet-api 那个依赖，的运行范围也只有在 编译和测试时使用，但有可能是Eclipse的原因，因为Eclipse，新建WEB项目时，会自动帮我们引入， 不用我们自己导入 servlet-api 这个包，这时应该就会冲突，把你的错误，贴出来看看，我这个小项目没在Eclipse 测试过，但IDEA部署项目到Tomcat的方式与Eclipse 不同，这也可能是出错的原因

**Comment by JaceyRx** [comment]
beanutils的包 在  shro-core 包的 依赖里，就自动被引入了， ibatis我看了项目依赖包里，没这个啊.....
