### ISSUE TITLE
关于项目学习

### ISSUE THREAD

**Issue by mccken** [JaceyRx/Examination_System#2]
你好，我最近在学习你这个项目，仿照你的项目做系统。现在有一些不懂的问题，希望能够获得你的联系方式

**Comment by nickalc** [comment]
@mccken 请问你的能启动起来吗

**Comment by JaceyRx** [comment]
@nickalc 你的不能运行起来吗？ @mccken 他的可以运行起来

**Comment by jxnu-liguobin** [comment]
我只想说项目是各种错误

**Comment by JaceyRx** [comment]
@jxnu-liguobin 能明确一点吗？是项目跑不起来，还是项目代码逻辑不通什么的

**Comment by Hitaylor** [comment]
我用netbeans编译的，但是报错如下：
严重:   Exception while loading the app
严重:   Undeployment failed for context /Examination_system/
严重:   Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [/WEB-INF/classes/spring/applicationContext-*.xml]; nested exception is java.io.FileNotFoundException: ServletContext resource [/WEB-INF/classes/spring/] cannot be resolved to URL because it does not exist
能否提供更完整的文档呀？谢谢

**Comment by JaceyRx** [comment]
@Hitaylor  你有没有用Maven编译一遍项目？你的这个错误是 target/classes/  目录下，找不到 [/WEB-INF/classes/spring/applicationContext-*.xml] 文件，也就是Spring的配置文件，觉得可能是你编译有时的问题..............

**Comment by Hitaylor** [comment]
我在idea和netbeans中都采用maven编译了，也用了“根据依赖关系编译”，都没有成功。我对Spring不熟悉，看文档里没有说指定配置文件之类的，我看resource目录下有几个配置文件，不知道怎么配置。谢谢。

**Comment by Hitaylor** [comment]
我使用maven进行了clean和compile，得到target目录以及examination_system.war,然后我选择target中的Examination_System中的login.jsp运行。仍然无法执行。我又将war文件放到tomcat的webapps目录中，仍然无法运行啊。

**Comment by leitiannian** [comment]
用eclipse无法运行啊，  404错误。     能不能加个qq给解决一下  谢谢  386502782

**Comment by OneIT-Dog** [comment]
您好！最近在学习您的项目，请问有问题能加QQ详细咨询吗？我的QQ是416497502 谢谢了！

**Comment by ungenius** [comment]
@Hitaylor @JaceyRx 哈哈我也出现那样的问题了，然后在网上找了两个小时，慢慢解决了，这个项目部的pom.xml中没有将resources目录编译进去，你打开你现在导入项目的web.xml会发现有两处错误，其中一个可以在pom.xml中加上这个
     <resource>
        <directory>${basedir}/src/main/resources</directory>
      </resource>
但是我的web.xml中spring容器<param-value>还是报错，就将它改成了<param-value>classpath:spring/applicationContext-*.xml</param-value>这个。
然后运行项目就可以了......
哈哈还有一个小坑，就是在配置tomcat的时候，使application context保持"/"就可以，不要自己加目录名

**Comment by ungenius** [comment]
<code>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
      </resource>
</code>

**Comment by ungenius** [comment]
`<resource>
        <directory>${basedir}/src/main/resources</directory>
      </resource>`

**Comment by amoxuk** [comment]
pom.xml里面加上<resource> <directory>${basedir}/src/main/resources</directory> </resource> 启动tomcat就可以了

**Comment by vrmight** [comment]
我用eclipse导入时一直报web.xml is missing and <failOnMissingWebXml> is set to true 但是这个文件有的啊,有人遇到这个问题么?

**Comment by vrmight** [comment]
有没有大佬用eclipse导入成功并且成功运行的? 求帮我弄一下..

**Comment by RushTop** [comment]
@JaceyRx  请问一下为什么 http://localhost:8080/Examination_System/login.jsp 会报404错误。我是用eclipse打成war包放到Tomcat中运行的

**Comment by CustomFN** [comment]
@JaceyRx 项目运行成功了，但是登录的时候又报错了，请问是为什么？
Type Status Report

Message /login

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by ttxs0109** [comment]
你好，项目运行起来，静态资源怎么全是404你们有吗？

**Comment by aimerwhy** [comment]
@JaceyRx  你好 登录后报404错误，请问是什么原因啊？

**Comment by Timeriovo** [comment]
@yiyuan0109 我跟你一样，很麻烦。你弄好了吗

**Comment by Timeriovo** [comment]
我的项目也是各种错

**Comment by Zeng1998** [comment]
![1](https://user-images.githubusercontent.com/31177490/35479576-0a25369e-0436-11e8-885c-7f57abdd8c89.png)
![2](https://user-images.githubusercontent.com/31177490/35479578-0af213bc-0436-11e8-87a8-1546229c9f72.png)
想请问为什么会这样，跑不起来？？

**Comment by Zeng1998** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collegeServiceImpl': Unsatisfied dependency expressed through field 'collegeMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.system.mapper.CollegeMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
能帮忙解答一下吗？？？

**Comment by leitiannian** [comment]
你这是bean没注入到Spring容器里吧

发自我的 iPhone

**Comment by dulestar** [comment]
@JaceyRx 你好，类拷贝BeanUtils这个方法有些使用的是spring的，有些使用的是apache的，两个参数左右赋值顺序不一样，为什么不统一一下，避免混淆。

**Comment by Junyerw** [comment]
你好,请问可以和你可以交流一下吗,QQ3130482720,谢谢

**Comment by mccken** [comment]
> 你好，我最近在学习你这个项目，仿照你的项目做系统。现在有一些不懂的问题，希望能够获得你的联系方式，最好是QQ，方便点。
> 我的QQ是747807013，谢谢
